### ISSUE TITLE
Make sniproxy obsolete

### ISSUE THREAD

**Issue by doino-gretchenliev** [steamcache/generic#106]
### Describe the issue you are having
Having to run two separate containers for HTTP and HTTPS traffic: monolithic and sniproxy.

### Solution
By using the Nginx `stream_ssl_preread` module you can add the following configuration to nginx.conf file:
```
stream {
    server {
        resolver UPSTREAM_DNS;
        listen      443;
        proxy_pass  $ssl_preread_server_name:443;
        ssl_preread on;
    }
}
...
http { ... }
``` 
and have the sniproxy functionally inside the main game cache container.

**Comment by VibroAxe** [comment]
This functionality was added in #107 you can now choose to run sniproxy or ssi embedded into generic/monolithic.

Thanks for the suggestion
