### ISSUE TITLE
cache_test.sh doesn't work

### ISSUE THREAD

**Issue by csm10495** [steamcache/generic#108]
### Describe the issue you are having
cache_test.sh uses  http://www.lagado.com/tools/cache-test as its url. Unfortunately, if you curl that address, you'll see that it just tries to redirect you to the https version instead of actually giving back useful data.

### How are you running the container(s)

NA

### DNS Configuration

NA

### Output of container(s)

```
root@bae5d3b77139:/scripts# curl http://www.lagado.com/tools/cache-test
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>CloudFront</center>
</body>
</html>
```

**Comment by VibroAxe** [comment]
Well spotted! We'll have to switch to a different (probably self hosted) test URL. Thanks

**Comment by csm10495** [comment]
@VibroAxe what about using http://worldtimeapi.org/api/timezone/America/New_York ?

**Comment by VibroAxe** [comment]
@csm10495 been a while but now looking into this, going to use http://worldtimeapi.org/api/timezone/ETC/GMT instead to not bias a timezone, but should be coming soon. Thanks for the idea
