### ISSUE TITLE
[Suggestion] Dashbord for Monitoring and Log Output

### ISSUE THREAD

**Issue by official-Cromatin** [steamcache/generic#115]
I've been looking for a long time, at home I run game servers for several friends, so updates have to be downloaded from scratch for each server, which in my opinion is an unnecessary burden on my already scarce bandwidth.

I installed the cache and adjusted the entries in the clients, and it just works fine.
Now i've been looking for several dashboards, also found a repo but haven't been able to get it to work yet.

I would be happy if an official dashboard would be available as an option, there you could e.g. Monitor traffic, size, users, and number of cached games, and spot errors.

You could monitor the data traffic from NGINX and display it, as well as read out and display the logs, but the essential information would still be missing

Regards

**Comment by RealFascinated** [comment]
I would love this too.
