### ISSUE TITLE
Blizzard not updating

### ISSUE THREAD

**Issue by ekhoury2000** [steamcache/generic#12]
Hi, @mintopia @mikeweyandt  @GotenXiao  @astrolox  @JasonRivers,

I was trying to use generic image with steamcache and steamcache-dns.

I installed the generic image on another server, it seemed to work fine, but now blizzard is not updating

Any idea? Is it working fien for you guys?

Best Regards,

**Comment by adrianmace** [comment]
Came here to log an issue about this. Blizzard not working on my fresh install at our Internet Cafe of 80+ computers either.

It's not just this steamcache either. Our mate's own edition [opensourcelan/origin-docker](https://github.com/opensourcelan/origin-docker) is also making clients fail to connect when downloading updates with similar DNS entries.

**Comment by astrolox** [comment]
Thanks for reporting this.

**Comment by Thr3d** [comment]
A reply from the nginx mailing list recommends a fix for the ETag issue with Blizzards CDN and sounds like it also has other desirable affects. This was also used in ti-mo/ansible-lanparty. I've been seeing Etag issues for some time now and this seems to have resolved it for me.

Example error:
`[error] 20#20: *4161 etag mismatch in slice response, client: 10.0.0.100, server: , request: "GET /tpr/pro/data/db/1f/db1faa8860dfe0c8e51407cc62ac0569 HTTP/1.1", subrequest: "/tpr/pro/data/db/1f/db1faa8860dfe0c8e51407cc62ac0569", host: "blzddist1-a.akamaihd.net"`

https://forum.nginx.org/read.php?29,271744,271750#msg-271750

> Try
> 
> `proxy_hide_header ETag;`
> 
> instead, it should help.
> 
> The other side effect of this is that there will be no ETag in
> responses returned. This is clearly a good thing in the scenario
> described, as ETag in your case is broken as it changes from one
> request to another. Removing it altogether will also help clients
> to use range requests and local caching.

**Comment by TestCandidate** [comment]
Any Progress on this? 
Origin is not updating for me either :( makes the whole thing unuable

**Comment by Scaredycrow** [comment]
Having similar problems here. Running four containers: Steamcache, generic, steamcache-dns and sniproxy. As yet the Steam caching is working great, but Blizzard (Overwatch) errors out on download of the game (about 4GB into the process!). Attached the Access and Error log from the generic cache for your perusal. There are plenty of errors, mostly stating "etag mismatch in slice response while reading response header from upstream. 

Happy to provide any extra info required to help diagnose. 

[generic-logs.zip](https://github.com/steamcache/generic/files/1346357/generic-logs.zip)

**Comment by mscrnt** [comment]
I've been spending the last few days trying to setup a LANCache, for Steam and Blizzard games, and I am having issues downloading Heroes of the Storm.

I am currently using Steamcache/Generic with Docker on Ubuntu 16.04. Overwatch downloads/caches with no issues and so does all Steam games.

While trying to download Heroes of the Storm, I am flooded with this message in my error.log

>2017/11/03 21:13:42 [error] 9#9: *23960 etag mismatch in slice response, client: 192.168.0.150, server: , request: "GET /tpr/Hero-Live-a/data/a9/ff/a9ffbffa31bbe89213c11d350cd282ff HTTP/1.1", subrequest: "/tpr/Hero-Live-a/data/a9/ff/a9ffbffa31bbe89213c11d350cd282ff", host: "blzddist1-a.akamaihd.net"

**Comment by mintopia** [comment]
Should be fixed in the 2017-updates branch. This is on dockerhub now - if you can re-test and let me know how it goes for you.

**Comment by mscrnt** [comment]
Definitely seems fixed now. Able to download and reinstall Heroes of the Storm and StarCraft with no issues. 

Thanks

**Comment by astrolox** [comment]
Fixed by #21  now merged to master
