### ISSUE TITLE
Add PlayStation Network compatibility

### ISSUE THREAD

**Issue by AlpacaDesu** [steamcache/generic#13]
Any plans of adding PlayStation Network compatibility too? 

(edited by admin)

**Comment by astrolox** [comment]
PlayStation Network is not something we've had a need to look in to.
If it's just HTTP then there's a good chance it will may just work, or need only minor changes.
Are you able to provide any technical details?

**Comment by AlpacaDesu** [comment]
I'm not that well versed with these, so I don't think I can provide the
technical details. I did see a few other LANcache forks that supported it,
but everything had some issue or the other.

**Comment by astrolox** [comment]
I think we should support this, and will be able to get the technical information from somewhere.
I'll leave this issue open on github as a way of tracking that we'd like to do this in the future. 
Unfortunately I can't commit to a timeline for it being done.

**Comment by JasonRivers** [comment]
I can possibly check out what my PS3 does, but I don't have aPS4 so I won't know if that'll be different.

**Comment by mintopia** [comment]
The cache should be compatible with PSN. The hostnames you'll need are:

- pls.patch.station.sony.com
- gs2.ww.prod.dl.playstation.net
- gs2.sonycoment.loris-e.llnwd.net

Taken from [bntjah/lancache](https://github.com/bntjah/lancache/blob/master/unbound/unbound.conf)
