### ISSUE TITLE
HTTPS 443

### ISSUE THREAD

**Issue by ekhoury2000** [steamcache/generic#14]
Hi @mintopia 

I was having an issue with generic image (blizzard client not updating), and then i noticed i was running sniproxy with generic image which obviously caused a conflict since they both use 443 TCP port.

Can i run lancache without listening to 443 port? AFAIK the sniproxy should be used to redirect https traffic to avoid the MITM scenario.

Please advise,

**Comment by mintopia** [comment]
The base image (nginx:alpine) exposes 443, you're correct that it's not required. I'll work on resolving that.

As a workaround, I'd suggest not using Host networking and instead use bridged networking and expose only port 80 on the container.

**Comment by ekhoury2000** [comment]
Hi @mintopia 
Thanks for the quick reply.

You mean adding --net=host while running the image? Please can u give me more info if otherwise

**Comment by mintopia** [comment]
@ekhoury2000 How are you currently running it? nginx itself isn't binding to 443 and the only thing that's stating 443 is the alpine-nginx base image.

**Comment by ekhoury2000** [comment]
@mintopia 

i am using redirection to redirect cached data to a shared storage

**Comment by mintopia** [comment]
You're running it correctly. I can't see any reason there why it would bind to port 443, even with it exposed in the base image, it's not going to bind it if you're not exposing it with -p.

I've just tested myself with that command line and the only port being bound is the one I specify. Can you provide a netstat from your server showing all listening ports and the processes listening?

`sudo netstat -lpn`

**Comment by ekhoury2000** [comment]
[PORTS.txt](https://github.com/steamcache/generic/files/910706/PORTS.txt)

@mintopia  Attached
Thanks

**Comment by mintopia** [comment]
Thanks for that, can you also provide a `docker ps` and a `docker port <container>` for the cache containers please?

**Comment by ekhoury2000** [comment]
[PORTS.txt](https://github.com/steamcache/generic/files/910726/PORTS.txt)
attache a new ports file since i have stopped the image before.

All attached thanks @mintopia

**Comment by mintopia** [comment]
So looking at the first netstat without the image running, there is already something listening on IPv6 443. If you provide the `docker ps` we can see what image/container is running.

I can't see a way the generic image could be bound to port 443.

**Comment by ekhoury2000** [comment]
@mintopia  As mentioned, my initial issue is that battle net client is getting stuck and not updating.

Any idea why?

i noticed also that port 443 was bound to IPV6, i will check how to disable on ubuntu and share.

**Comment by mintopia** [comment]
The Battle.net client might be getting stuck because it's trying to do HTTPS to one of the hostnames we're intercepting. Without the SNI Proxy running, it'll be unable to connect and will fail.

I was using the generic image and SNI Proxy last weekend at an event and had no problems with lots of people playing Overwatch.

*edit* Just looked at your updated PORTS.txt. It looks OK with the containers. Whilst 443 is exposed steamcache/generic, because nothing is actual bound to it, it won't be causing a problem.

Are there any logs in Battle.net about it?

**Comment by ekhoury2000** [comment]
@mintopia I need to cache steam and Riot and blizzard games.

Can you please advise if you have a better setup or maybe better images to run?

**Comment by mintopia** [comment]
Everything you're doing seems correct. The changes I'd make would be to run them all on the same server and have multiple instances of the cache, one for each thing you're caching.

Add multiple IPs to your network interfaces in Ubuntu then run the containers and specify the IP in the -p parameter, eg:

```
docker run --name cache_blizzard --restart=always -d -v /srv/cache-blizzard/data:/data/ -p 192.168.1.10:80:80 steamcache/generic:latest
docker run --name cache_riot --restart=always -d -v /srv/cache-riot/data:/data/ -p 192.168.1.11:80:80 steamcache/generic:latest
docker run --name cache_steam --restart=always -d -v /srv/cache-steam/data:/data/ -p 192.168.1.12:80:80 steamcache/generic:latest
docker run --name cache_sniproxy --restart=always -d -v -p 0.0.0.0:443:443 steamcache/sniproxy:latest
```

In this example, I've switched your steam cache to use the generic image instead. You can use either for Steam, my personal preference is to use the generic image as it handles certain failure scenarios better, but is harder to maintain the cache files on disk.

**Comment by ekhoury2000** [comment]
ok @mintopia  Thanks for the help. will do as you said and test and let u know.

Thanks again

**Comment by ekhoury2000** [comment]
@mintopia One more question, with the line up you proposed, which dns server you use? steamcache-dns? and how do you bind it with all those ip addresses? or you just use static dns entries?

I just read that in steamcache-dns, you can set an ip for ech service, but even when done, i still get no resolve when i try l3cdn.riotgames.com or any other.

should i add dns records for blizzard and riot in order to resolve them correctly? like db.blizzard? and how will the format be?

**Comment by mintopia** [comment]
I personally use a separate DNS server as I have an authoritative DNS server already for the LAN to use and it was easier for me to implement it all in that DNS server.

Using the steamcache-dns container, you should need to set RIOTCACHE_IP to the right IP address.

If you look at logs for the steamcache-dns container, it should print out if the cache is enabled for Riot. If it's enabled, it should say "Enabling cache for Riot".

**Comment by ekhoury2000** [comment]
@mintopia  i have a DNS Server also running on my router, but adding entries for riot and blizzard is easy, but steam is the problem.

If i configure steamcache-dns as my first dns server, it will override the entries on my router and send the client requesting riot and blizzard directly online

Thanks for your help

**Comment by mintopia** [comment]
There's two things you can do:

1. Set `-e RIOTCACHE_IP=192.168.1.10 -e BLIZZARDCACHE_IP=192.168.1.11` (swap out the IPs for yours) on the steamcache-dns container. This will tell it to forward those zones to your cache server.
2. Use `--dns=192.168.1.1` (use your LAN DNS server) on steamcache-dns. I *think* this should make it use your DNS server for recursive queries.

The DNS container isn't something I really get involved with as I don't use it.

**Comment by ekhoury2000** [comment]
@mintopia Thanks for the help i appreciate it.

i had set the -e riotcache_ip=192.168.1.7 as shown in my previous comment, but as shown in cache.conf for steamcache-dns:  

## Windows
#ENABLE_WINDOWS#zone "download.windowsupdate.com" in { type master; file "/etc/bind/cache/windows/db.windows"; };

it seems to read dns entries and search for them in db.widnows file for windows, etc...

my question was do we need to add entries to the file db.windows? and what is the format?

**Comment by mintopia** [comment]
cache.conf has sections for all known services:

https://github.com/steamcache/steamcache-dns/blob/master/overlay/etc/bind/cache.conf

As long as RIOTCACHE_IP is set, it should enable the Riot section on the config. (this is done in bootstrap.sh)

**Comment by ekhoury2000** [comment]
@mintopia Ok thanks a lot, i will test right away

Thanks again

**Comment by ekhoury2000** [comment]
Hi @mintopia 

I just finished and was testing with riot LOL.

Getting error when running the games, i think the issue is that generic image is actually listening to port 443 and conflicting with sniproxy.

Is there any way i stop it or disable it?

i tried telnet on the ip of the generic image telnet 192.168.1.6 443 and port was opened.

Thanks

**Comment by mintopia** [comment]
Whilst the generic image does expose port 443 in the dockerfile (from the base nginx image), unless you tell docker to pass the port through using `-p` or run it in host network mode, the port will never be bound on your network interface on the machine hosting it.

If you used the commands I gave you further up the thread, the SNI Proxy will be bound to all IP addresses on port 443, and that is what you should end up telnet'ing to.

If you stop the docker image for the SNI Proxy, you should then find that you cannot telnet to port 443 and netstat will no longer show anything listening on port 443.

I plan to do some work on the image this week to prevent it from exposing port 443 at all, however this shouldn't be causing you any problems.

**Comment by ekhoury2000** [comment]
@mintopia OK i get it thank you, but why is LOL not opening with errors in logs:

[rads_user_kernel.txt](https://github.com/steamcache/generic/files/912682/rads_user_kernel.txt)

I guess i will face the same issues with battle net too and origin. :(

**Comment by mintopia** [comment]
I'm not in a position to do testing here at the moment, looking at your logfile:

The client is requesting `http://l3cdn.riotgames.com/releases/live/projects/lol_launcher/releases/releaselisting_EUNE`. Try requesting this file in your browser (which will go via your cache). You should see it appear in the access logs for the cache server (/data/logs/access.log inside the container)

I think this part of it is working correctly. The next bit however fails:

```
(  DEBUG)[12:11:05.779] RADS::Common::HTTPConnection::HTTPConnection: (http://127.0.0.1)
(  DEBUG)[12:11:05.779] RADS::Common::HTTPConnection::Connect: (http://127.0.0.1)
(  ERROR)[12:11:06.810] RADS::Common::HTTPConnection::GetFile: perform request failed with code 7
(  ERROR)[12:11:06.810] RADS::Common::HTTPConnection::GetFile: Failed on /rest/getToken?format=xml&ClientID=PMB_Client
```

This looks like it's trying to make a HTTP request to 127.0.0.1 - do you have any local DNS/hostfile entries that might be redirecting anything for Riot to 127.0.0.1?

**Comment by ekhoury2000** [comment]
No DNS or Hosts entries :( i also tested blizzard and its going directly to the internet :(

**Comment by mintopia** [comment]
This is almost getting into support for steamcache-dns, but if Blizzard is going directly out to the Internet then it would suggest you're not intercepting the DNS correctly. When you do an nslookup for `llnw.blizzard.com`, what IP do you get?

**Comment by ekhoury2000** [comment]
@mintopia i get the ip of the server i configured. my dns is working fine i did all the tests. ping and nslookup all return my intenel ip addresses. for the 127.0.0.1, could it be from the hosts file inside the image?

**Comment by mintopia** [comment]
OK, you need to look at the access logs on the cache server then. First time installing something through the cache you should see cache MISS in the logs, second time you should see cache HITs.

I tested Blizzard less than 2 weeks ago and it was working fine at the time. It's possible Blizzard have changed something since then.

When you're updating the game, run Resource Monitor and have a look at the hostnames that battle.net downloader is trying to download from, hopefully it'll all be your local cache server IP. If it's not, then there are additional hostnames we need to intercept.

**Comment by ekhoury2000** [comment]
@mintopia Seems Riot had server issues, Now i think its working.

Will keep you posted

**Comment by mintopia** [comment]
Thanks Riot...

In that case I'll close this for now. If the problems re-occur, please re-open it!
