### ISSUE TITLE
tool to prefill the cache before a lan with common gamefiles

### ISSUE THREAD

**Issue by wofnull** [steamcache/generic#17]
A nice feature additional to the toolchain from the generic / steamcache itself would be to prefill the Cache with actual content beforehand a bigger event. 

The way i solve it until now is to predownload a "most common" set of games through the gameservices. depending on the Client this uses much time for micromanaging to delete the local installs.

How about a tool that uses functions from the steamcmd tool, to download a set of specific game IDs, and delete them afterwards and/or if possible for other plattforms aswell.

**Comment by astrolox** [comment]
I believe that @mintopia has such a tool already. I don't know if it is in a state that can be shared.

The main limitation with doing this is that you can only download games that you own.

**Comment by wofnull** [comment]
and as far as i could see it currently only supports steam aswell

**Comment by mintopia** [comment]
It';s a good idea and something I've been doing for a couple of years. Works exactly as you'd suggested using steamcmd. It will also download versions for all platforms.
There are a couple of tools to do this.

- https://github.com/mintopia/steamcache-primer
- https://github.com/zeropingheroes/lancache-autofill

They both use steamcmd and require you to own the games that are being primed.
