### ISSUE TITLE
Majority of Requests Missed for Steam

### ISSUE THREAD

**Issue by jjohnson338** [steamcache/generic#18]
It seems the majority of the requests to steam miss because steam responds in HTTP 302 most of the time (which, in code, isn't cached).

Is there anything I can do to fix this on my end to make this more useful? Caching for blizzard works wonderfully, but that is mostly HTTP 200.

**Comment by ekhoury2000** [comment]
Hi @jjohnson338 ,

Are u able to cache blizzard downloads? If yes can u please give me more info about ur setup?

**Comment by jjohnson338** [comment]
So I tried to reproduce the issue last night to capture some logs to post here, but all the games I downloaded on steam responded to each request with an HTTP 200 and was properly cached. I'm not very well versed in anything but basic HTTP protocol so my guesses may sound dumb but I'm guessing maybe certain games result in a majority of HTTP 302 or Steam had some abnormal load the night I installed steamcache/generic and redirected requests for their purposes.
