### ISSUE TITLE
Support for Sony, Hi-Rex, Tera, etc.

### ISSUE THREAD

**Issue by saip92** [steamcache/generic#19]
This [project](https://github.com/bntjah/lancache/blob/master/unbound/unbound.conf) has a bunch of other redirects that would be great if integrated into steamcache as well.

Using that project directly is surely an option but steamcache is super easy to get up and running with its docker support and IMHO seems much simpler to me.

**Comment by mintopia** [comment]
This is probably best raised in the DNS project. This cache should be generic enough to be used by most of those other cache providers, and it doesn't require any additional config for each one.

- Add an additional IP to the host server
- Run a new container for the service you want to cache, set a new directory for cache data and bind to a new IP
- Add DNS entries for the services you want to cache.

In my case, I'm running 9 instances of this generic container for caching Steam, Frontier, MS Updates, Workshop, UPlay, Origin, Battle.net, Steam Workshop and Hirez.

I will update the readme.md with more hostnames.

**Comment by mintopia** [comment]
I've updated the readme and linked to another project that is maintaining the hostnames.
