### ISSUE TITLE
Permission denied after Docker run command

### ISSUE THREAD

**Issue by Meinen** [steamcache/generic#24]
Hello,

I am having trouble deploying the Docker container the way it is documented.
When I run this command:
docker run --restart unless-stopped --name cache-steam -v /cache/steam/data:/data/cache -v /cache/steam/logs:/data/logs -p 10.0.2.15:80:80 steamcache/generic:latest

As its documented under: https://hub.docker.com/r/steamcache/generic/
I only recieve this error Message:
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
2017/12/12 12:36:38 [emerg] 10#10: mkdir() "/data/cache/cache" failed (13: Permission denied)
nginx: [emerg] mkdir() "/data/cache/cache" failed (13: Permission denied)
nginx: configuration file /etc/nginx/nginx.conf test failed

When I try and run the Docker passing only "-v /cache/steam:/data" like this:
docker run --restart unless-stopped --name cache-steam -v /cache/steam:/data -p 10.0.2.15:80:80 steamcache/generic:latest

the container actually starts successfully, created the "/cache/steam/data" and "/cache/steam/logs" directorys and even caches Steam downloads, but the internal Docker folder /data is not linked to /cache/steam on the Server itself.

The internal directorys look like this:
docker exec cache-steam /bin/sh -c "ls -al /data/cache"
total 12
drwxr-xr-x    3 nginx    nginx         4096 Dec 12 12:56 .
drwxr-xr-x    4 root     root          4096 Dec 12 12:27 ..
drwx------    2 nginx    root          4096 Dec 12 12:56 cache

e.g: /data/cache/cache

Did I miss a step in the configuration or is the Documentation simply outdated?

Cheers,
Finn

**Comment by mintopia** [comment]
Hi Finn,

Docker will need write permissions on the directory on the host that you're mounting in; also create the logs and data directories on your host.

Let me know how that works for you.

Thanks!

**Comment by Meinen** [comment]
Hi Jessica,

I did set the permission to 777 for testing, but that didn't work either.
[root@localhost steam]# ls -al
insgesamt 20
drwxrwxrwx. 5 root root 4096 12. Dez 15:52 .
drwxrwxrwx. 8 root root 4096 12. Dez 13:56 ..
drwxrwxrwx. 2 root root 4096 12. Dez 13:27 cache
drwxrwxrwx. 2 root root 4096 12. Dez 15:52 data
drwxrwxrwx. 2 root root 4096 12. Dez 13:27 logs

Here I created a file through the Docker but it doesn't exist on the host.
[root@localhost steam]# tree
.
├── cache
├── data
└── logs

3 directories, 0 files
[root@localhost steam]# docker exec cache-steam /bin/sh -c "cd /data/cache; ls -al"
total 12
drwxr-xr-x    3 nginx    nginx         4096 Dec 12 14:52 .
drwxrwxrwx    5 root     root          4096 Dec 12 14:52 ..
drwx------    2 nginx    root          4096 Dec 12 14:53 cache
[root@localhost steam]# docker exec cache-steam /bin/sh -c "cd /data/cache/cache; ls -al"
total 8
drwx------    2 nginx    root          4096 Dec 12 14:53 .
drwxr-xr-x    3 nginx    nginx         4096 Dec 12 14:52 ..
-rw-r--r--    1 root     root             0 Dec 12 14:53 test

Since I ran the "docker run" as root it was even able to create the Directorys on startup.

Thanks for your help!

**Comment by mintopia** [comment]
Your original run command should have worked.

```
docker run --restart unless-stopped --name cache-steam -v /cache/steam/data:/data/cache -v /cache/steam/logs:/data/logs -p 10.0.2.15:80:80 steamcache/generic:latest
```

The only thing I would have done before running it is to create the /cache/steam/data and /cache/steam/logs directories.

What OS are you running docker under?

**Comment by Meinen** [comment]
I am currently testing on a Fedora 27 Machine with "docker-1.13.1-42.git4402c09.fc27.src.rpm" from the Fedora repositorys.
At home I had the same issues on a CentOS 7 Host which is supposed to become the productive cacheserver.

Creating the folders beforehand sadly didn't help either.

**Comment by Meinen** [comment]
I gave it another try on Ubuntu 16.04 and it is working flawlessly.
Not my favorite distro but it will work for the next LAN :).

The docker version here is 1.10... I might install this version manually on the CentOS7 Host to see if this is the problem.

**Comment by Meinen** [comment]
I gave it another try on Ubuntu 16.04 and it is working flawlessly.
Not my favorite distro but it will work for the next LAN :).

The docker version here is 1.10... I might install this version manually on the CentOS7 Host to see if this is the problem.
