### ISSUE TITLE
Add RSI (Star citizen)

### ISSUE THREAD

**Issue by nuhll** [steamcache/generic#25]
Hi,
could you add RSI Downloader (Star Citizen?) Its always huge GB to download.

Thanks.

**Comment by mintopia** [comment]
The cache doesn't have a list of services it supports. You can point anything at it. A comprehensive list of games/download systems that have been used with it and the domain names can be found here.

 - https://github.com/uklans/cache-domains

I don't have Star Citizen so have no idea how it does downloads; but if the domain names are unique and its HTTP, then you could cache it.
