### ISSUE TITLE
Implement proxy_cache_key change

### ISSUE THREAD

**Issue by taylor-j-hawkins** [steamcache/generic#26]
The generic image appears to suffer from the same issue described [here,](https://github.com/steamcache/steamcache/issues/18) in the steamcache image. 

Would it be possible to have this implemented for the generic image as well in order to improve caching?

Currently, a game has to be downloaded 6+ times in order to get enough saturation of chunks to guarantee the local cache is used.

**Comment by mintopia** [comment]
proxy_cache_key is` $uri$slice_range`, Valve content is unsliced, so that won't affect it. `$uri` doesn't include the hostname, just the path.

Since content is cached without the hostname, it wouldn't be affected by the issue you linked.

**Comment by taylor-j-hawkins** [comment]
Appreciate the response mintopia, please bear with me, I'm sure I have plenty of knowledge gaps. 

If that's the case then what would you speculate the issue to be? 

Currently, what I observe is chunks being downloaded from a 'randomly' selected steam content server each time the download is initiated. If the game being downloaded is 5GB I have to keep redownloading the game until the cache is roughly 20GB in order to have enough saturation of chunks to ensure that most of the chunks are downloaded from the local cache instead of being requested from a different content server.

**Comment by nuhll** [comment]
Yea, i have the same,i test my cache only with one game all time (if i change something in network).

I dont know how many times i downloaded it (10+), but im not able to do 3/4 over lan. Mostly 1/4 or maybe half. 

The issue was posted some time ago and it still happens, isnt that the whole point of this cache to cache atleast 90% or something!?

Origin, with some heavy changes does like 100%, all time.

(and no,. cache is not full or too old)

**Comment by mintopia** [comment]
Hi @nuhll , I replied with something similar in your other issue on the steamcache/steamcache project.

This config is setup to cache anything sent to it through DNS redirection. It makes the upstream request using nginx's proxy functionality. The cache key only includes the slice range and the URI, it does not include the hostname - so it doesn't matter what upstream host the cache pulls from, it will still be stored in the same place. If you are getting problems where it's only caching a quarter of the content, then it's likely you are not intercepting the DNS on all hostnames.

You can find a list of all hostnames discovered so far at the [UK LANs Cache Domains Project](https://github.com/uklans/cache-domains/blob/master/steam.txt). You can check what content server hostnames your PC is using by looking in the logs directory inside your Steam directory.

There is a logfile `content_log.txt`. If the cache is not working for a hostname you will see something like this with a public IP (in this case 162.254.196.37) listed:

```
[2017-11-09 08:08:05] HTTP (CS,427) - valve427.steampipe.steamcontent.com (162.254.196.37:80 / 162.254.196.37:80, host: valve427.steamcontent.com): alve427.steampipe.steamcontent.com/depot/326411/manifest/5910737621358100731/5 - received 200 (OK) HTTP response
```

In this example, you can see from the first entry that I need to be intercepting DNS for `valve427.steamcontent.com`. The UK LANs cache domain list says to cache *.steamcontent.com, so if I add DNS for that, it will work.

If your cache is working, that IP will be your cache IP instead, for example:

```
[2018-02-21 12:43:40] HTTP (CS,429) - valve429.steampipe.steamcontent.com (10.10.0.11:80 / 10.10.0.11:80, host: valve429.steamcontent.com): alve429.steampipe.steamcontent.com/depot/228986/manifest/1003373983685403880/5 - received 200 (OK) HTTP response
```
I hope this helps.

**Comment by taylor-j-hawkins** [comment]
I believe I have actually discovered the root of my issue: https://github.com/steamcache/steamcache-dns/issues/26

It appears that Comcast is running their own mirrors edge.steam-dns.top.comcast.net that I am not redirecting DNS for.
