### ISSUE TITLE
Steam Cache generating 302 while downloading Steam Client

### ISSUE THREAD

**Issue by alexholliz** [steamcache/generic#29]
We're using the the Generic Steamcache in our environment, and we've run into an issue this morning where the steam client is failing to download. Took a peek in the error log, and this is what I am seeing:

`2018/03/06 16:10:33 [error] 10#10: *95612 unexpected status code 302 in slice response while reading response header from upstream, client: 10.16.10.158, server: , request: "GET /client/bins_webhelpers_win32.zip.vz.c05f07ba6a52429edb32cd7b40e04d5f638f4697_1095795 HTTP/1.1", subrequest: "/client/bins_webhelpers_win32.zip.vz.c05f07ba6a52429edb32cd7b40e04d5f638f4697_1095795", upstream: "http://162.254.192.11:80/client/bins_webhelpers_win32.zip.vz.c05f07ba6a52429edb32cd7b40e04d5f638f4697_1095795", host: "client-download.steampowered.com"`

Any ideas on how I could mitigate this? My research on this showed that I need to increase the proxy buffer size in nginx, which I can totally do, but it means modifying the container.

As an added note, the error the user gets is as follows:
"Steam needs to be online to update. Please confirm your network connection and try again"

**Comment by mohsinskynet** [comment]
where to find nginx file to change the CACHE_MEM_SIZE, CACHE_DISK_SIZE, CACHE_MAX_AGE
and how to run Game Content Cache Hostnames please post a guide or tell here ty

**Comment by mintopia** [comment]
Can't reproduce this issue locally. If you can reliably reproduce it - please let me know and re-open this.

**Comment by mskafi** [comment]
Generic cache generates unexpected status code 302 in slice response while reading response header from upstream while trying to cache
```
2019/05/11 22:32:09 [error] 42#42: *120953 unexpected status code 302 in slice response while reading response header from upstream, client: 192.168.200.42, server: , request: "GET /gs2/ppkgo/prod/CUSA02168_00/55/f_852143d164a5c3a84ad75ae5cd5e1c4458e31010be1fd8794dcaeb28fec61ccf/f/EP9001-CUSA02168_00-GTSPORT000000000-A0138-V0100_10.pkg?downloadId=000000a9&du=00000000000000a900e248a22cdf490c&product=0187&threadId=0&serverIpAddr=192.168.200.207&r=00000001&downloadType=om HTTP/1.1", subrequest: "/gs2/ppkgo/prod/CUSA02168_00/55/f_852143d164a5c3a84ad75ae5cd5e1c4458e31010be1fd8794dcaeb28fec61ccf/f/EP9001-CUSA02168_00-GTSPORT000000000-A0138-V0100_10.pkg", upstream: "http://87.248.222.128:80/gs2/ppkgo/prod/CUSA02168_00/55/f_852143d164a5c3a84ad75ae5cd5e1c4458e31010be1fd8794dcaeb28fec61ccf/f/EP9001-CUSA02168_00-GTSPORT000000000-A0138-V0100_10.pkg?downloadId=000000a9&du=00000000000000a900e248a22cdf490c&product=0187&threadId=0&serverIpAddr=192.168.200.207&r=00000001&downloadType=om", host: "gs2.ww.prod.dl.playstation.net"
```

This is happening on multiple deployments. Any ideas? (I am using the uklans/cache-domains for sony servers)

**Comment by alexholliz** [comment]
I had to increase the slice size to some arbitrarily large number, like 700m. This cleared up the 302 errors, but I still don’t have an explanation as to *why* they’re happening in the first place.

**Comment by joseph743** [comment]
@alexholliz  where did you change it?

**Comment by alexholliz** [comment]
Look for:

```
  location / {
    #Cache Location
    slice 200m;
    proxy_cache generic;
```

In the nginx config
