### ISSUE TITLE
Slow speed and no shop at steam.

### ISSUE THREAD

**Issue by Fischje** [steamcache/generic#3]
Using generic now, defined al zones for steam and other platform direct at my sophos firewall to route to the steamcache:generic.
Works fine at start. Now 2 Probem:
1. At battle.net i got only a very reduced speed, like 1 Mbit/s (6Mbit/s peer). Docker runs, but the cpu and the memory is not the problem i see at docker stats.
2. At steam a i can install games at my library, the steam-store at the steamsotware generates "error -137" and does not work.

Any suggestions on this probs?

**Comment by Fischje** [comment]
speedproblem was a setting at battle.net - shame on me..... sry.
only the 2. problem is actual....

**Comment by GotenXiao** [comment]
The Steam store shouldn't be affected by the setup we provide in the steamcache-dns container - have you accidentally overridden the top level record for steampowered.com? Double check that your zones match the ones defined under https://github.com/steamcache/steamcache-dns/blob/master/overlay/etc/bind/steamcache.conf, if you're not running our DNS container.

**Comment by pyro2927** [comment]
I'm running both like [this](https://github.com/steamcache/generic/issues/6#issuecomment-282203588) and am seeing the the `-137` error when Steam pops up the "deals selected for you" bit.

**Comment by chasqui1607** [comment]
Sometimes it happens to me, othertimes the content server stores first http based page and uses it in any page based on http (that includes steam store), any solution?

**Comment by astrolox** [comment]
I'm sorry but we don't see the same problem. 

You said "no shop", are you also running the [SNI proxy](https://github.com/steamcache/sniproxy)? If not, this will help.

**Comment by mintopia** [comment]
Closing - possibly due to SNI Proxy, I've been unable to reproduce this.
