### ISSUE TITLE
everything is working okay ?

### ISSUE THREAD

**Issue by tamatoa** [steamcache/generic#31]
I would like to know if this repo works flawless as I see so many docker steamcache and dont know which to pick. I would like something to cache all games from any editors. Thank you

**Comment by JasonRivers** [comment]
We use this image at multiple LANs, some of which are 500+ users.
The only caveat is that it does NOT work with EPIC games (unreal tournament, fortnight, etc) as they use HTTPS to distribute their games making it near impossible to cache. You should run a seperate container per service (Steam, Origin, Uplay, Etc) to avoid cache clashing. Please refer to the README file for more information.

**Comment by mohsinskynet** [comment]
where to find nginx file to change the CACHE_MEM_SIZE, CACHE_DISK_SIZE,  CACHE_MAX_AGE
and how to run Game Content Cache Hostnames please post a guide or tell here ty

**Comment by mintopia** [comment]
@mohsinskynet Please don't reply to every single issue. Raise a new issue with your problems.

**Comment by mintopia** [comment]
Closing issue as original issue has been dealt with.
