### ISSUE TITLE
caching issue

### ISSUE THREAD

**Issue by mohsinskynet** [steamcache/generic#35]
hey there caching is working awesome but it will cache all the things on 80 http not just steam can someone help me to get rid of

**Comment by JasonRivers** [comment]
Please could you share how you're starting the containers and what your DNS config is?
The container is setup to cache any HTTP data that goes through it, so the DNS should be set to only point to this image for the service you wish to cache, If you point all traffic to the image as a proxy it will cache everything.

**Comment by mohsinskynet** [comment]
problem solved i just uninstall and re-install lan cache of ryan and it worked well then this  ty for the reply
