### ISSUE TITLE
110 Operation timed out

### ISSUE THREAD

**Issue by a2theziz** [steamcache/generic#38]
My caching server suddenly started getting upstream time outs. I didn't make any changes to my configuration so I'm not sure what's causing it

I have Steamcache's sniproxy/generic/steamdns installed in containers on my Synology NAS.

Error I'm getting:

2018/08/08 09:49:44 [error] 27#27: *1036 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 192.168.0.3, server: , request: "GET /depot/420291/manifest/3127109883701325934/5?l=14&e=1534280479&sid=14638906&h=6bac8f454f2ab671ed054b10ce47ca4dd5410947 HTTP/1.1", upstream: "http://162.254.197.12:80/depot/420291/manifest/3127109883701325934/5?l=14&e=1534280479&sid=14638906&h=6bac8f454f2ab671ed054b10ce47ca4dd5410947", host: "valve502.steamcontent.com"

If I try testing it manually by going to the upstream link: [http://162.254.197.12:80/depot/420291/manifest/3127109883701325934/5?l=14&e=1534280479&sid=14638906&h=6bac8f454f2ab671ed054b10ce47ca4dd5410947](url) 

I get unauthorized.

But if I include the hostname it works:

[http://valve502.steamcontent.com/depot/420291/manifest/3127109883701325934/5?l=14&e=1534280479&sid=14638906&h=6bac8f454f2ab671ed054b10ce47ca4dd5410947](url)

**Comment by a2theziz** [comment]
Issue resolved itself.

**Comment by mskafi** [comment]
I had a similar issue. It only got resolved when we cleared cache (and first by uninstalling Steam completely from the system.)

**Comment by JasonRivers** [comment]
The original issue looks like it may have been a temporary glitch from the steam servers (you shouldn't see unauthorized unless valve did something), @arithma you may have had a cache expiry, This is something that has come up in a few conversations about the caching systems, Currently we have no way of telling that a cache should expire, we are working on ways to do this.
