### ISSUE TITLE
League of Legends doesnt work

### ISSUE THREAD

**Issue by agassparkle** [steamcache/generic#39]
While downloading League of legends it downloads until a certain point and than gives a error 004.
When i delete the DNS it downloads again.

**Comment by mintopia** [comment]
Can you provide any logfiles from the docker container, using `docker logs <container id>`, that might show any errors, or from any logging in the League client.

We're not aware of any issues currently affecting caching for LoL.

**Comment by mintopia** [comment]
The other thing to ensure is that you are running the [SNI Proxy container](https://github.com/steamcache/sniproxy). Details are in the readme and FAQ. It needs to listen on port 443 on the same IP as the cache server. It is used to pass through HTTPS traffic and is required for LoL and Blizzard.
