### ISSUE TITLE
[SUGGESTION] Epic Games

### ISSUE THREAD

**Issue by kuletxcore** [steamcache/generic#42]
Can we expect Epic Games support in the future? (Fortnite, Unreal Tournament, UE4, etc.)

Thanks!

**Comment by MikeTheGreek** [comment]
Hi kuletxcore , this is completely dependent on Epic.
It is not possible to cache the Epic launcher because it uses HTTPS to download content. They would need to change to HTTP for downloads.

**Comment by mintopia** [comment]
Hi,

This is covered in the [FAQ](https://github.com/steamcache/generic/blob/master/faq.md). The container can cache any HTTP based service.

Unfortunately, Epic use HTTPS, so it's not possible to cache it.

Thanks,
Mintopia
