### ISSUE TITLE
No logon in Steam possible

### ISSUE THREAD

**Issue by Timon321** [steamcache/generic#44]
Hey guys,

at first -> cool project!

But i have a problem with loggin in to steam. It hangs at "Connection with Steam-Account ***"
In the log of the Docker-Container 'steam-cache' there are many logs of the ngnix with MISS:

`10.10.10.27 / - - - [23/Aug/2018:20:10:07 +0000] "GET /depot/252494/chunk/129705e028733989abfdef19c458c9e83261cdbd?l=14&e=1535659709&h=535e57032c1551bafbfc220656bc0796 HTTP/1.1" 200 316464 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cdn.highwinds.cs.steampowered.com" "-"
10.10.10.27 / - - - [23/Aug/2018:20:10:07 +0000] "GET /depot/252494/chunk/bd1a68c7a0a939fcebe3c03c05240669320a611a?l=14&e=1535659709&h=535e57032c1551bafbfc220656bc0796 HTTP/1.1" 200 465264 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cdn.highwinds.cs.steampowered.com" "-"
10.10.10.27 / - - - [23/Aug/2018:20:10:07 +0000] "GET /depot/252494/chunk/a1fa4bf66bb639230f1799f0fe966ba1fa52dc3d?l=14&e=1535659709&h=535e57032c1551bafbfc220656bc0796 HTTP/1.1" 200 27593 "-" "Valve/Steam HTTP Client 1.0" "MISS" "cdn.highwinds.cs.steampowered.com" "-"`

Maybe i am not alone with this problem?

**Comment by mintopia** [comment]
Hi,

Cache MISS is expected in the logs, it shows that the cache had to fetch that file from the remote server. You should also start seeing cache HIT in the logs as it finds content that is already on the cache.

I'm not sure why you're having issues logging into Steam, it may be due to your DNS configuration - how have you configured DNS?

Thanks,
Mintopia

**Comment by Timon321** [comment]
DNS Configuration is set via DHCP.
Primary is set to 10.10.10.190. Secondary at domain controller.

IPs from proxy-machine:
1. Physical + Steam: 10.10.10.190
2. Origin: 10.10.10.191
3. Blizzard: 10.10.10.192

Origin and Blizzard are working flawless.

**Should i use an extra IP for the Steam container?**

The steamcache-dns is started with following command:
```
sudo docker run \
  --restart unless-stopped -d \
  --name steamcache-dns \
  -p 10.10.10.190:53:53/udp \
  -e UPSTREAM_DNS=10.10.10.10 (Domain Controller) \
  -e STEAMCACHE_IP=10.10.10.190 \
  -e ORIGINCACHE_IP=10.10.10.191 \
  -e BLIZZARDCACHE_IP=10.10.10.192 \
  steamcache/steamcache-dns:latest
```

**Comment by mintopia** [comment]
The config looks OK.

There are logfiles in the Steam client directory. Have look at those and see if they contain any information that might help.

**Comment by mintopia** [comment]
Please re-open the issue if you have the steam client logfiles.
