### ISSUE TITLE
Cannot for the life of me figure out why I cant run watchlog.SH 

### ISSUE THREAD

**Issue by MartinMac1982** [steamcache/generic#46]
So I have searched online and I can't find the cause of my issue at all, I have all my containers up and running but I cannot figure out why when I run the : 

 docker exec -it steam-cache /scripts/watchlog.sh

commannd it just returns this every time:

OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"/scripts/watchlog.sh\": stat /scripts/watchlog.sh: no such file or directory": unknown

Following are the containers I have running:

sudo docker ps
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                      NAMES
cd9394c087f5        steamcache/steamcache-dns:latest   "bash /scripts/boots…"   8 hours ago         Up 3 seconds        192.168.1.142:53->53/udp   steamcache-dns
24192243e997        steamcache/sniproxy:latest         "sniproxy -f"            9 hours ago         Up 8 hours          0.0.0.0:443->443/tcp       sniproxy
f20a8c4a43c8        steamcache/generic:latest          "/scripts/bootstrap.…"   9 hours ago         Up 8 hours          192.168.1.146:80->80/tcp   uplay-cache
23744b50368b        steamcache/generic:latest          "/scripts/bootstrap.…"   9 hours ago         Up 8 hours          192.168.1.145:80->80/tcp   windows-cache
1c3a35a7db33        steamcache/generic:latest          "/scripts/bootstrap.…"   9 hours ago         Up 8 hours          192.168.1.144:80->80/tcp   blizzard-cache
de3c152902be        steamcache/generic:latest          "/scripts/bootstrap.…"   9 hours ago         Up 8 hours          192.168.1.143:80->80/tcp   origin-cache
2ad98fb607f9        steamcache/generic:latest          "/scripts/bootstrap.…"   9 hours ago         Up 8 hours          192.168.1.142:80->80/tcp   steam-cache

Any help would be much appreciated.

**Comment by MartinMac1982** [comment]
I'm also getting really slow transfer speeds when I view the traffic with the nload command rarely hitting even 2MB/s on a 300Mbit/s connection , regardless whether its me downloading a game to the caching server for the first time through my windows pc or if its directly from the caching server.

**Comment by mintopia** [comment]
It's not really reccomended you use watchlog.sh as it can be quite CPU intensive. Try using executing bash directly and specifying watchlog.sh instead.

Or even ```docker exec -it steam-cache /bin/bash``` then in interactive shell, just run watchlog.sh.

For performance - what spec are you running the cache server on? It's very RAM and disk IO dependent.

**Comment by MartinMac1982** [comment]
I am running it on a spare PC I had laying around 4GB RAM , 4 core cpu. 3 x 2TB SATA 3 drives (mechanical) in a raid zero array (for speed) to store the cache on (although the drive I have the OS installed on is on old SATA 2 laptop 500gb mechanical drive).

I think part of my issue is due to incorrect or bad ethernet drivers being installed. I have no idea how to check or fix this though in Linux. Both this machine and my windows gaming machine are connected to the same router , both have gigabit network cards but when I run an internet speed test from the Linux box I get 50Mb/s yet my gaming PC gives me 300Mb/s. Weird.

**Comment by mintopia** [comment]
I've never had to care about drivers in linux, but I tend to stick to Intel NICs so they don't cause issues.

The mechanical drives, even RAID 0 will still probably cause the cache to max-out around 300-600mbps.

It might be worth running more speed tests using iperf or the commandline speedtest client from your linux server to benchmark the network performance.

**Comment by MartinMac1982** [comment]
Yeah but I'm barely getting that when it's coming from my cache

**Comment by mintopia** [comment]
So you're getting around 300-600mbps on content being served directly from the cache? If so, I'd say with mechanical disks, and only 4GB RAM, you're not going to get much better.

**Comment by MartinMac1982** [comment]
In my earlier comment I posted that I'm getting 2MB/s from the cache when downloading in steam and that my internet speed from my ISP is 300mb/s NOT that I'm getting the 300mb/s from the steamcache server.

**Comment by mintopia** [comment]
I see. You should be getting better performance than that really. The thing to check is definitely CPU usage, disk io performance/iowait, etc. The software itself is proven on high-end hardware to peak at 10gbps at large LAN parties.

If it's slow on initial downloads, it might be worth checking the write speed to the disk for the cache. If it's slow writing data, it may slow downloads from the Internet.

**Comment by MartinMac1982** [comment]
So I got my Linux box all up and running and serving files (I checked the watchlogs) weird thing is steam keeps dropping the connecting every 20 seconds or so it stops to zero speed. This is during the portion when my PC should be going to the internet to download the field initially before the steamcache serves them up.

I have checked the cpu utilization and ram and disk access and none of this seems to be an issue. I have also tried to set the DNS server ok either my router or ok my clients ethernet settings. I run regular speed tests and I get my 300MB/s internet connection even on the Linux box using ooklas speed test. For some reason steam just wants to do the initial download super slow.

**Comment by MartinMac1982** [comment]
So I'm not sure entirely what I changed that fixed it. but I just downloaded my first game successfully from the Steamcache LAN server without it going to the internet. The speeds i showed on Steam at the time were somewhere in the 3-400 Mbps range with the peak being 466.4 given that my current internet connection maxes out at 280-300Mbps on a good day I would say this is now working.

I would still like to get the LAN speeds to be faster though so that is going to be my next project.

**Comment by JasonRivers** [comment]
Closing as the original issue is solved.

@MartinMac1982 regarding the speed, there's many things that could cause this, read/write speed on the cache, Other systems using the cache, the client system disk write speed, other services using the disk on the client.

The best test we've done is on the steamcache is the using steamcmd on a linux system with a RAMFS mounted so that speed on the client is not an issue.

If you continue to have issues that are not to do with watchlog.sh, please raise a fresh issue.
