### ISSUE TITLE
If I use steamcache-dns with generic, do I still need to add the DNS entries required by the README?

### ISSUE THREAD

**Issue by tgharib** [steamcache/generic#5]
I am mainly referring to these: https://github.com/steamcache/generic#dns-entries

Sorry, not a network expert and had a bit of trouble with the docs.

I am looking to cache Steam + Battle.NET + Origin using the generic image.

**Comment by GotenXiao** [comment]
If you're using our DNS container as your primary DNS, then no - it will serve as authoritative for the required DNS for all services, then fall back to Google's DNS for everything else. You will need to configure your DHCP to point all clients at that IP though, or if you're using something like `dnsmasq`, configure a domain override to point the entire CDN root domain at the steamcache-dns IP.

The steamcache-dns [README](https://github.com/steamcache/steamcache-dns) has more details on usage, but for caching all services with a single container service (that is, not running the dedicated steamcache container separately), you'll want to invoke the DNS container like so:
`docker run --name steamcache-dns -p 10.0.0.2:53:53/udp -e STEAMCACHE_IP=10.0.0.4 -e USE_GENERIC_CACHE=true -e LANCACHE_IP=10.0.0.4 steamcache/steamcache-dns:latest`
where 10.0.0.4 is the IP of your cache host.

If you want to be able to copy the cache data from your steamcache onto another instance, then it's generally recommended to use the dedicated steamcache container separately, as it creates a more usable mirroring of the cache content.

**Comment by tgharib** [comment]
Thank you! I appreciate the clarification.

**Comment by sta3b** [comment]
@GotenXiao heyy, i used this command : docker run --name steamcache-dns -p 10.0.0.2:53:53/udp -e STEAMCACHE_IP=10.0.0.4 -e USE_GENERIC_CACHE=true -e LANCACHE_IP=10.0.0.4 steamcache/steamcache-dns:latest

it downloads the dns just fine then it goes like this 
running bootstrap.sh..
enabling cache for blizzard
enabling cache for steam
bootstrap finished
checking bind9 config
running bind9

it get stuck on running bind9 and nothing happens, any idea why ? thanks!
