### ISSUE TITLE
Windows Updates Not Caching

### ISSUE THREAD

**Issue by ghost** [steamcache/generic#52]
As the title says, windows updates are no longer caching. In fact they ajust hange when routed through generic cache.

**Comment by matthewh86** [comment]
Post your config!

Could be this?

https://github.com/steamcache/steamcache-dns/issues/44

**Comment by ghost** [comment]
Config? Do you mean how I run the container?

**Comment by ghost** [comment]
`docker run --name='SteamCache' --net='br0' --ip='192.168.1.5' -e 'CACHE_MEM_SIZE'='5000m' -e 'CACHE_DISK_SIZE'='2000g' -e 'CACHE_MAX_AGE'='150d' -v '/mnt/user/appdata/gen-cache/data/':'/data/cache':'rw' -v '/mnt/user/appdata/gen-cache/logs':'/data/logs':'rw' 'steamcache/generic:latest'`

**Comment by matthewh86** [comment]
What steamcache-dns config are you using? Have you tried the [docker-compose](https://github.com/steamcache/docker-compose) provided instead of running them separately?

**Comment by JasonRivers** [comment]
We are tracking this issue here: https://github.com/uklans/cache-domains/issues/39

For the moment, please use DISABLE_WSUS=true on the dns container.

**Comment by VibroAxe** [comment]
https://github.com/uklans/cache-domains/issues/39 is closed so this should now be working
