### ISSUE TITLE
caching on blizzard is stuck

### ISSUE THREAD

**Issue by sta3b** [steamcache/generic#60]
hello, caching on blizzard is having some issues, several gaming lounges reported the issue.
As soon as i stopped the container that was running blizzard cache and stopped the dns re-route downloads worked fine
issues : blizzard app is stuck on 0% and does not update , game updates also stuck or run for a while and then hang with a download speed reaching 0-25b/s
im running those commands :

sudo docker run --name cache-steam --restart=always -d -v /cache/steam/data:/data/cache -v /cache/steam/logs:/data/logs -p 192.168.88.68:80:80 steamcache/generic:latest

sudo docker run --name cache-blizzard --restart=always -d -v /cache/blizzard/data:/data/cache -v /cache/blizzard/logs:/data/logs -p 192.168.88.69:80:80 steamcache/generic:latest

sudo docker run --name steamcache-dns --restart=always -p 192.168.88.68:53:53/udp -e CACHE_MAX_AGE=95d -e UPSTREAM_DNS=1.1.1.1 -e STEAMCACHE_IP=192.168.88.68 -e BLIZZARDCACHE_IP=192.168.88.69 -e DISABLE_RIOT=true -e DISABLE_FRONTIER=true -e DISABLE_ORIGIN=true -e DISABLE_WINDOWS=true steamcache/steamcache-dns:latest

note that the caching was working fine for the past couple of months, suddenly the blizzard issue came up in several gaming lounges

**Comment by mintopia** [comment]
Try running the SNI Proxy docker image as well. It's possible there is mixed content on some of the hostnames for Blizzard. We now recommend you always run the steamcache/sniproxy container on all IP addresses on port 443.

Give it a go and let us know if it doesn't work.

**Comment by sta3b** [comment]
hello, i always run SNI Proxy, i tried disabling it but same issue
command : 
sudo docker run --name prox --restart=always -d -p 443:443 steamcache/sniproxy:latest

should i try running sniproxy via -p 192.168.88.69:443:443 ?

**Comment by sta3b** [comment]
i just got some more reports about the same issue elsewhere, something must be wrong with blizzard
i'm just gona disable the caching for blizzard until the issue is resolved

**Comment by slimshizn** [comment]
This started for me when Destiny 2 was announced free till the 16th of Nov. Started the download and it kept giving me issues. Haven't seen this before.

**Comment by sta3b** [comment]
yeah, blizzard app is stuck, games updates are stuck on fetching files .. dno

**Comment by binatra** [comment]
this was happening to me too. What was interesting is that it started to work after i've changed the UPSTREAM_IP from 8.8.4.4 to 8.8.8.8 , and on client side i did that to and it started to download and to cache.

**Comment by sta3b** [comment]
Hello, i always use upstream dns 1.1.1.1 or 8.8.8.8
And of course if you switch the client dns it will download normally cz it overrides the cache dns
I think upstream dns is not working properly because when downloads get stuck it doesnt switch to 8.8.8.8, its like hanging on the dns of the cache server and not overriding it if there is an issue with the download

**Comment by slimshizn** [comment]
If there is a problem still why was this closed?

**Comment by sta3b** [comment]
hello @slimshizn , turned out cache is working fine for most of the cybercafes, but the issue is happening with only cafes using a specific ISP, errors logs would result :  

2018/12/08 18:56:33 [error] 22#22: *122 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.88.252, server: , request: "GET /tpr/bnt001/patch/42/9a/429a8daceed1276a50a4bb59b4beca6e.index HTTP/1.1", upstream: "http://95.101.114.18:80/tpr/bnt001/patch/42/9a/429a8daceed1276a50a4bb59b4beca6e.index", host: "blzddist1-a.akamaihd.net"
2018/12/08 18:56:33 [error] 22#22: *122 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.88.252, server: , request: "GET /tpr/bnt001/patch/42/9a/429a8daceed1276a50a4bb59b4beca6e.index HTTP/1.1", upstream: "http://95.101.114.26:80/tpr/bnt001/patch/42/9a/429a8daceed1276a50a4bb59b4beca6e.index", host: "blzddist1-a.akamaihd.net"

as you can see, problem is with AKAMAI, so i contacted the ISP and showed them the logs and issue should be resolved in the next couple of days.  you should be having the same issue with ur ISP

**Comment by VibroAxe** [comment]
@sta3b was that the error log from generic/nginx?

**Comment by sta3b** [comment]
@VibroAxe yes from steamcache generic

**Comment by sta3b** [comment]
@VibroAxe if i bypass the cache  and use 1.1.1.1 or 8.8.8.8 on any pc , it works fine, its just hanging when i switch the dns to the cache server, its like it fails to reroute me to 1.1.1.1

**Comment by sta3b** [comment]
@VibroAxe any info would be appreciated since i am working with the ISP too to try to solve this matter
thank you

**Comment by sta3b** [comment]
@VibroAxe , this is after i created a new cache depot for blizzard : (error logs from steamcache generic)

2018/12/11 18:44:32 [error] 30#30: *13 unexpected status code 200 in slice response while reading response header from upstream, client: 192.168.88.252, server: , request: "GET /tpr/ovw/patch/be/bb/bebb108ee2d1be9841827f9d8f0875d3 HTTP/1.1", subrequest: "/tpr/ovw/patch/be/bb/bebb108ee2d1be9841827f9d8f0875d3", upstream: "http://2.18.212.48:80/tpr/ovw/patch/be/bb/bebb108ee2d1be9841827f9d8f0875d3", host: "blzddist1-a.akamaihd.net"
2018/12/11 18:45:17 [error] 25#25: *51 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 192.168.88.252, server: , request: "GET /tpr/hs/data/98/38/9838400604865fee9cd33cfa11d0c72c HTTP/1.1", upstream: "http://2.18.212.10:80/tpr/hs/data/98/38/9838400604865fee9cd33cfa11d0c72c", host: "blzddist1-a.akamaihd.net"

**Comment by sta3b** [comment]
@VibroAxe , 1 more thing , in the access log , i get this line and it keeps generating itself infinitely :  

192.168.88.252 / - - - [11/Dec/2018:18:52:11 +0000] "HEAD /tpr/hs/config/be/d7/bed7ece46686cb04309090c2a88db068 HTTP/1.1" 200 0 "-" "-" "HIT" "blzddist1-a.akamaihd.net" "-"

**Comment by sta3b** [comment]
@VibroAxe for other gaming lounges, i have the same setup but i use 2 different network cards, 1 for steam, 1 for blizzard, would that solve the issue if i do the same on the current "not working" cache servers ? the "not working blizzard cache servers" currently running steam cache and blizzard cache on the same network card and the network card has 2 IP addresses assigned to it

**Comment by sta3b** [comment]
@VibroAxe i installed a second network card to the pc and ran blizzard cache on it, worked perfectly.
so if the issue is happening to anyone, run each cache depot on a different network card
