### ISSUE TITLE
steamcache image failing to be processed

### ISSUE THREAD

**Issue by BrianGitt** [steamcache/generic#64]
Hi,
Im running ubunto 18.04 desktop edition on vmWARE(using windows os)with a 100 GB given space.

when i run  this code: 
sudo docker run \
  --restart unless-stopped -d \
  --name steam-cache \
  -v /home/user/cache/steam/data:/data/cache \
  -v /home/user/cache/steam/logs:/data/logs \
  -p 192.168.1.50:80:80 \
  steamcache/generic:latest
 
### **Result:**latest: Pulling from steamcache/generic
4fe2ade4980c: Pull complete 
e11b023b07a0: Pull complete 
aaf7d5908de5: Pull complete 
8ae3a5ca453f: Pull complete 
b494cbfdaa4c: Pull complete 
489e1e313017: Pull complete 
Digest: sha256:04d20e341efbe344dc8cda6dea56e90a8801cc1194277d0afb289879943ea4ef
Status: Downloaded newer image for steamcache/generic:latest
4660032cc496b4dd3cfac2753ebf7c38c068bb4262324b7e6a667c641f34b35f
docker: Error response from daemon: driver failed programming external connectivity on endpoint steam-cachee (921438246a6a4ba7fc0233335883bde17af1c1b30c186f3478f7108ab4166d1f): Error starting userland proxy: listen tcp 192.168.1.50:80: bind: cannot assign requested address.

### PS: my router ip is 192.168.1.1 ( and there is no one on my network having this ip)
user is my 'username'

Please help ! 👍

**Comment by mintopia** [comment]
Hi,

The error suggests you already have something listening on port 80 on that IP. Are you running a webserver on the server?

**Comment by BrianGitt** [comment]
hi, 
I checked there is nothing listening on port 80, even i changed the ip, same error 

thank you for your reply

**Comment by VibroAxe** [comment]
Have you assigned 192.168.1.50 to the machine in question.

Can you please paste the output of the following commands
`ip a`
`netstat -nlpt`

**Comment by BrianGitt** [comment]
okay, thank for the reply again 

i did all the steps and everything is working fine, but it is not caching.
my question is : 
can we apply this procedure through Virtualbox with ubunto on it? Host pc platform is windows 10.﻿

**Comment by BrianGitt** [comment]
Okay all good and working, i switched to virtualbox instead of vmWARE workstation.
