### ISSUE TITLE
Cache doesn't appear to being used

### ISSUE THREAD

**Issue by BurningTheSky** [steamcache/generic#76]
### Describe the issue you are having
I have set up and got the docker running for the steam cache but when I download a game I can't see any data being stored in the folders and the logs don't appear to show anything being pulled

### How are you running the container(s)?
docker run --restart=always --name cache-steam -v /mnt/usb/steamcache/data:/data/cache -v /mnt/usb/steamcache/logs:/data/logs -p 192.168.1.20:80:80   steamcache/generic:latest

### DNS Configuration
At first I just put in CNAMES into Windows Server 2016 DNS for all the Steam entries and did test nslookups which resolved correctly. As I didn't see any requests going through the cache log I changed to:
docker run --name steamcache-dns -p 192.168.1.29:53:53/udp -e STEAMCACHE_IP=192.168.1.20 steamcache/steamcache-dns:latest

### Output of container(s)
Only shows a couple of requests from my phone to check the web interface was up, last game download was around 09:50:
root@ubuntu:~# docker exec -it cache-steam tail -f /data/logs/access.log
127.0.0.1 / - - - [20/Jan/2019:02:11:09 +0000] "GET /steamcache-heartbeat HTTP/1.1" 204 0 "-" "Wget/1.19.4 (linux-gnu)" "-" "127.0.0.1" "-"
127.0.0.1 / - - - [20/Jan/2019:03:11:10 +0000] "GET /steamcache-heartbeat HTTP/1.1" 204 0 "-" "Wget/1.19.4 (linux-gnu)" "-" "127.0.0.1" "-"
127.0.0.1 / - - - [20/Jan/2019:04:11:11 +0000] "GET /steamcache-heartbeat HTTP/1.1" 204 0 "-" "Wget/1.19.4 (linux-gnu)" "-" "127.0.0.1" "-"
127.0.0.1 / - - - [20/Jan/2019:05:11:13 +0000] "GET /steamcache-heartbeat HTTP/1.1" 204 0 "-" "Wget/1.19.4 (linux-gnu)" "-" "127.0.0.1" "-"
127.0.0.1 / - - - [20/Jan/2019:06:11:14 +0000] "GET /steamcache-heartbeat HTTP/1.1" 204 0 "-" "Wget/1.19.4 (linux-gnu)" "-" "127.0.0.1" "-"
127.0.0.1 / - - - [20/Jan/2019:07:11:15 +0000] "GET /steamcache-heartbeat HTTP/1.1" 204 0 "-" "Wget/1.19.4 (linux-gnu)" "-" "127.0.0.1" "-"
127.0.0.1 / - - - [20/Jan/2019:08:11:16 +0000] "GET /steamcache-heartbeat HTTP/1.1" 204 0 "-" "Wget/1.19.4 (linux-gnu)" "-" "127.0.0.1" "-"
192.168.1.100 / - - - [20/Jan/2019:08:45:51 +0000] "GET / HTTP/1.1" 502 584 "-" "Mozilla/5.0 (Linux; Android 9; Pixel 2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Mobile Safari/537.36" "MISS" "steamcache.cs.steampowered.com" "-"
192.168.1.100 / - - - [20/Jan/2019:08:45:51 +0000] "GET /favicon.ico HTTP/1.1" 502 584 "http://steamcache.cs.steampowered.com/" "Mozilla/5.0 (Linux; Android 9; Pixel 2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Mobile Safari/537.36" "MISS" "steamcache.cs.steampowered.com" "-"
127.0.0.1 / - - - [20/Jan/2019:09:11:17 +0000] "GET /steamcache-heartbeat HTTP/1.1" 204 0 "-" "Wget/1.19.4 (linux-gnu)" "-" "127.0.0.1" "-"

I notice that the heartbeat doesn't appear to be still running but the docker is still up I believe:
root@ubuntu:~docker ps
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                              NAMES
06fa00383b5a        steamcache/steamcache-dns:latest   "bash /scripts/boots…"   27 minutes ago      Up 27 minutes       192.168.1.29:53->53/udp            steamcache-dns
994ef86d5a7b        steamcache/generic:latest          "/bin/bash -e /init/…"   12 hours ago        Up 12 hours         192.168.1.20:80->80/tcp, 443/tcp   cache-steam

Am I missing something obvious?

**Comment by VibroAxe** [comment]
At a guess your not pointing to the correct dns servers. Have you updated your computer/network dns to point to 192.168.1.29:53

Also, am I correct that your docker server has two ips 192.168.1.20 and 192.168.1.29

Failing that, can you upload a copy of your content_log whilst downloading a game (On your steam directory is a logs directory. In there is a file called content_log.txt.)

**Comment by VibroAxe** [comment]
@BurningTheSky Any joy on the above?

**Comment by BurningTheSky** [comment]
I went back to this and redeployed the docker DNS, using it as an upstream DNS for the Windows DNS and it started to work. What is the correct way to get the Windows DNS to function without the docker or does it never really work?

**Comment by VibroAxe** [comment]
@BurningTheSky the only fully supported option is the steamcache-dns, we can give limited help with configuring bind/powerdns zones due to the team's experience but windows DNS isn't supported (thats not to say it wont work it definitely can, but more we don't have the expertise in windows dns)
