### ISSUE TITLE
Garena missing cache

### ISSUE THREAD

**Issue by nyemenzo** [steamcache/generic#78]
### Describe the issue you are having
i fork steamcache-dns and change bootstrap.sh to locate my edited repository that i fork from uklans/cache-domains. after i updated riot.txt with this lolph.cdn.gpipe.garenanow.com it is now caching files. but every time i download LOL in garena its MISS with no HIT

### How are you running the container(s)?
```
sudo docker run --restart=always --name cache-steam -d -p 192.168.8.10:80:80 -v /media/winshare/cache/steam/data:/data/cache -v /media/winshare/cache/steam/logs:/data/logs steamcache/steamcache:latest

sudo docker run --restart=always --name cache-wargaming -d -p 192.168.8.11:80:80 -v /media/winshare/cache/wargaming/data:/data/cache -v /media/winshare/cache/wargaming/logs:/data/logs steamcache/generic:latest

sudo docker run --restart=always --name cache-riot -d -p 192.168.8.12:80:80 -v /media/winshare/cache/riot/data:/data/cache -v /media/winshare/cache/riot/logs:/data/logs steamcache/generic:latest

sudo docker run --restart=always --name sniproxy -d -p 443:443 steamcache/sniproxy:latest
```

### DNS Configuration
i fork steamcache/dns and uklan/cache-domains and had some minor changes and build dockerfile form steamcache-dns. i just change to where to get domains instead geting to uklans i change it to the fork repo from uklan.
```
sudo docker run --restart=always --name steamcache-dns -d -p 192.168.8.10:53:53/udp -e 
STEAMCACHE_IP=192.168.8.10 -e WARGAMINGCACHE_IP=192.168.8.11 -e RIOTCACHE_IP=192.168.8.12 -e UPSTREAM_DNS=8.8.8.8 dropme123/mycache-domains:latest
```
![cache](https://user-images.githubusercontent.com/31677679/52677104-7f932f00-2f67-11e9-85f5-0e0bd0e8ef98.png)

**Comment by VibroAxe** [comment]
This isn't a riot problem, it's related to garena.

Can you please start with a fresh cache instance (delete all cached data) then try the following

1) download lol through garena, 
2) delete lol install (note the time)
3) download lol through garena

Then upload your entire access.log from generic and the times you started all 3 steps

**Comment by nyemenzo** [comment]
1. 13:47:05 - 13:30+ (pause and resume)
2. 14:06 (stop and delete)
3. 14:07 (re-download)

here is my access logs. and to be sure i will upload my error log because i see a bunch of errors. i just download until 12% just for testing because i do have an internet capping.
[access.log](https://github.com/steamcache/generic/files/2884951/access.log)
[error.log](https://github.com/steamcache/generic/files/2884952/error.log)

**Comment by VibroAxe** [comment]
The error logs seem to imply that whatever server is on the garena end isn't playing nicely and is terminating the connection abnormally

`2019/02/20 14:06:59 [error] 42#42: *4152 upstream prematurely closed connection while reading upstream, client: 192.168.8.8, server: , request: "GET /c0=/info_hash=09dfd6a81e1347d314f7c6c9885bbdb1a847a8bc/piece=0/length=131072 HTTP/1.1", upstream: "http://203.177.62.111:80/c0=/info_hash=09dfd6a81e1347d314f7c6c9885bbdb1a847a8bc/piece=0/length=131072", host: "lolph.cdn.gpipe.garenanow.com"`

I'm honestly not sure there's a lot we can do about this unless anyone has any ideas?

**Comment by nyemenzo** [comment]
hope there is. ahh! by the way, out of my curiosity i bump into this article maybe we can also apply it to fix the problem. https://github.com/owncloud/client/issues/5706

**Comment by nubpro** [comment]
Is there an update to this?
Did you managed to cache Garena?

**Comment by nyemenzo** [comment]
no.. i tried so hard but nothing happens.

**Comment by VibroAxe** [comment]
I'm afraid without access to garena this is hard for us to handle.

**Comment by nubpro** [comment]
My team has managed to pull this off rather easily.

1. Forked cache-domains git.
2. Added garena.txt and update cache_domains.json (refer to this repo: https://github.com/TA-Software/cache-domains)
3. Recompiled the lancache-dns docker with changes that points it to the above repo.

We've tried it and it seems to be caching Garena LoL just fine.

I will probably be submitting a PR for Garena games once we've performed a thorough testing in the next coming weeks.

**Comment by VibroAxe** [comment]
@nubpro thats excellent news if it's working. If you want to submit a PR to uklans i'll look at accepting it if it's working?

**Comment by nubpro** [comment]
Sounds awesome on my end, will submit the PR asap 👍

**Comment by nyemenzo** [comment]
You can cache it but you can get a hit.
