### ISSUE TITLE
Unable to update the Origin client when using the Origin cache function

### ISSUE THREAD

**Issue by JohanvdHoven** [steamcache/generic#8]
I am running a combined Steamcache/Lancache setup which works like a charm.
My Origin games are cached when I install them so a second installation will be taken care of by the local cache, like designed.

However, if the Origin client on my game PC needs to be updated, it keeps telling me to work offline and is unable to connect to the Origin cloud and download the client update files.
If I stop the Origin cache I can perform the Origin client update without any problem.

Not a big issue for me but less experienced users on my network will be confused by these extra steps...

**Comment by mintopia** [comment]
I think this is because Origin tries to make HTTPS requests to one of the hostnames that we have to use in the cache. The solution is to run sniproxy on the IP for the Origin cache. This will forward the HTTPS connections on to the actual server at Origin.

https://github.com/dlundquist/sniproxy
https://github.com/OpenSourceLAN/origin-docker

I'll push an image to dockerhub this week for it.

Give this a try and if it fixes the issue for you, let me know.

**Comment by JohanvdHoven** [comment]
Thank you for the quick response! Will try the new docker image when you make it available.
Would the Uplay client have the same issue?

**Comment by mintopia** [comment]
It might do, depends if it tries to use HTTPS to one of the hostnames that you're overriding. I run SNI Proxy and have it bound to 443 on every IP the cache uses, so it covers it regardless.

Didn't have any issues at a 480 person LAN party the other weekend (but I did have this problem with Origin last year before I started using SNI Proxy).

**Comment by JohanvdHoven** [comment]
Just tested the Uplay client and it behaves exactly like the Origin client.
Upon a fresh client installation the client tries to update itself and fails to do so.
Bypassing the cache "fixes" the problem so it looks like it might be a similar problem.

**Comment by kixelated** [comment]
Oh nice, I completely forgot about SNI. That's a much better solution than issuing untrusted certs like I was originally thinking.

**Comment by mintopia** [comment]
After last night's fun with AWS stopping dockerhub from working, I've built the image:

https://hub.docker.com/r/steamcache/sniproxy/

Give that a try and if it doesn't solve the problem, re-open the issue.

**Comment by JohanvdHoven** [comment]
Works like a charm! Thank you!
