### ISSUE TITLE
Changing IP adress of working cache server

### ISSUE THREAD

**Issue by drobskind** [steamcache/generic#87]
### Describe the issue you are having
I was not able to find an answer to my question anywere using google. Maybe I am just searching using the wrong words.

I have an cache server set up and running fine for all (steam, uplay, rockstar, wsus, etc.)
now I want to take it to another place for a small LAN party to handle the slow internet connection over there.

Problem is, the network there, is using a different ip-range. So the commands to startup the lancache docker container I used here are different.

What command do i have to use to change the ips of the existing and running containers?
When I just change the IP in the command and run it a second time, it will show an error message, that the container is already existing.
Is there any update command?

### How are you running the container(s)?
```
<!-- Paste your docker run commands or your docker-compose file here -->
```

### DNS Configuration
```
<!-- Paste your docker run command for the DNS container OR explain how you have setup DNS on your network to point to the container -->
```
### Output of container(s)
```
<!-- Paste any output from the containers here - This will help us identify any issues faster -->
```

**Comment by VibroAxe** [comment]
@drobskind to change the ip you will need destroy the container (`docker stop; docker rm`) and then create a new container with the new ip. 

This won't invalidate your cache data as it is stored outside the container and as such can be used by the new container
