### ISSUE TITLE
EA Origin Beta client now uses HTTPS

### ISSUE THREAD

**Issue by Neomancer86** [steamcache/generic#89]
Beta Client is now HTTPS - Would expect this to migrate to live in the near future. this will mean Origin will no longer be covered by the cache unless EA provide an alternative option or disable HTTPS

**Comment by gergc** [comment]
looks like as of friday or so this made it to live :\

**Comment by DragonQ** [comment]
Currently downloading an Origin update and it doesn't seem to be using lancache at all, so I guess Origin is currently broken despite me having a lancachenet/sniproxy docker container set up?

**Comment by VibroAxe** [comment]
@DragonQ due to the above issues origin is currently disabled in the upstream cache_domains. 

Sniproxy doesn't enable caching of https data it merely ensures that mixed content domains don't break completely. Any domain with no http content is not included in the cache_domains project

**Comment by unspec** [comment]
Origins efforts to provide a work around to https caching issues are being tracked here: https://github.com/uklans/cache-domains/issues/98 - updates will be posted there when available.
