### ISSUE TITLE
What is the data directory or directories used by lancache?

### ISSUE THREAD

**Issue by JohanvdHoven** [steamcache/generic#9]
I am redirecting the data created by the lancache docker (see my command line below).

sudo docker run --name lancache --restart=always -d -v /srv/lancache/data:/data/cache -v /srv/lancache/logs:/data/logs -p 10.0.0.12:80:80 steamcache/generic:latest

Are the /data/cache and the /data/logs the only directories I have to redirect?
Can I just redirect /data to /srv/lancache/data (or another directory on the computer running the cache) and get the same result?

**Comment by Thr3d** [comment]
Those are the only two needed for persistent cache files and logs. You'd need to use `/data/cache` and `/data/logs` separately otherwise they'll end up in the docker volume.

**Comment by JohanvdHoven** [comment]
Thank you for confirming what I concluded from my tests. Are the same folders used in the Steamcache docker?
