### ISSUE TITLE
HTTPS caching, self-signed SSL certificate, MITM

### ISSUE THREAD

**Issue by DMahalko** [steamcache/generic#91]
This is not a problem, just a comment.

HTTPS caching is possible if you set up the cache as a proxy server, create a self-signed SSL certificate, install the self-signed certificate on the cache server and the clients, and set the cache as the proxy for all traffic.

This allows the cache server to cache everything, HTTPS or not.

The downside is that the proxy cache can see all the raw HTTPS traffic accessed by clients, so it bypasses all security for any website using HTTPS accessed by the clients.

This is known as a man-in-the-middle security attack as the clients will explicitly trust the proxy cache due to the self-signed certificate and will not display any security warnings on the client devices.

Also without special filtering of certain SSL page content or URLs, it will end up caching things you do not want to cache, like the contents of shopping carts, bank account data, etc, so it can be challenging to make HTTPS proxy caching work properly.

Reference: https://stackoverflow.com/questions/14656/can-a-proxy-server-cache-ssl-gets-if-not-would-response-body-encryption-suffic

**Comment by astrolox** [comment]
We are aware of this. Given our target market is LAN parties, i.e. people running events where other people that they may not know very well bring their own hardware, we don't wish to be encouraging everyone to break the chain the trust inherent in SSL. We feel that this would be irresponsible of the project, and is a big part of the reason why we lobby all the big distribution platforms to continue to support both HTTPS and HTTP.

As an aside, check out our SNI proxy repo which is our solution for MITM DNS for lancache without breaking HTTPS. https://github.com/lancachenet/sniproxy
