### ISSUE TITLE
Cache Size suffix

### ISSUE THREAD

**Issue by joamla96** [steamcache/generic#95]
Hi.

Under the section [Tweaking Cache Sizes](https://github.com/lancachenet/generic#tweaking-cache-sizes) it's noted "500m" and "500000m".

is "m" the only suffix supported?
and would "m" be mb or mib?

**Comment by astrolox** [comment]
Interesting question.

Sizes can be specified in bytes, kibibytes (suffixes k and K) or mebibytes (suffixes m and M).

https://en.wikipedia.org/wiki/Kibibyte
https://simple.wikipedia.org/wiki/Mebibyte
